### ISSUE TITLE
Canada - 98.5 FM Montréal

### ISSUE THREAD

**Issue by simlevesque** [adblockradio/available-models#10]
Hi, it's a francophone station in Canada, here's what to look for on radio-browser.info:
"CHMP-FM 98,5 MHz FM, Montréal"

I can help with the filter ! I'd really want to help you get most important francophone stations in Canada.

**Comment by dest4** [comment]
Thanks for your suggestion and your offer to help!

Most of the software stack is ready for you to be able to help with the filters. My main concern is that I do not want adblockradio.com/player to be the unique player available, unless I get donations for the server costs. I can add one or two Canadian stations, but I will not add dozens of them.

What would help a lot right now would be to have other standalone players available.
That one is a first draft https://github.com/adblockradio/buffer-player

**Comment by simlevesque** [comment]
I'll host one, no problem. I'll also try my hand at making the metadata scraper for the station, it looks right in my alley, I do a lot of scraping work and I use axios too.

**Comment by dest4** [comment]
For the record, @simlevesque has labeled quite a lot of audio and the filter is behaving well. Thanks!

**Comment by dest4** [comment]
98.5 FM Montréal has been online for a few days now. Closing this request.
