### ISSUE TITLE
How can I create  prediction models for new music ?

### ISSUE THREAD

**Issue by SakethMadishetty** [adblockradio/available-models#9]
I want to check if two audio files matches or a portion of it matches. I want to create a sqlite db  for a source audio file by myself and the check if another audio file ( random recorded one) matches with it.
So, how can I create  a fingerprint db for new music?

**Comment by dest4** [comment]
Hello,
what you need is https://github.com/adblockradio/stream-audio-fingerprint to create the fingerprints.
then https://github.com/adblockradio/adblockradio/blob/master/predictor-db/hotlist.js to compare the results.

Your request is off topic here, so I am closing it.
